### PR TITLE
Animated Background

### LINKED ISSUE #9: Setting a Background
We want to add a background, possibly in the `Layout.tsx` so that it will be applied in every page.

We could also get a little inspired and create simple effects in the background, like:
- Smoothly moving the background as the mouse moves
- Having snow-like simple particles move
- Ducks running around...

We could also just set a simple static background for now.

### PR DESCRIPTION
**Pull request by ErtyumPX**
Closes #9 

## What are we doing with this PR?

- Using the animated background template from [here](https://codepen.io/stolinski/pen/DjoXVM)
- Arranging the colors according to our current themes, which we can quite easily change in the future
- Fixing unnecessary delay in Tremor inputs while toggling dark/light mode, by setting the transition duration to 0, apparently it is set to something other than 0 by default in their styles
- In the `Card` in the `Form` component, changing the border decoration from only top to top-left, I believe it is much better this way

## How does it look?

Unfortunatelly I cannot take a video, but here are some screenshots:

screenshot-2024-03-29_02:32:25

screenshot-2024-03-29_02:32:37

## What needs to be done as follow-up?

There is nothing needed as follow-up. As long as we need other stuff to do, we can leave the background in good-enough form...

## Notes

Definetely run the code and check the background animation, dark/light mode changes while reviewing.

### CODE REVIEW

**Review by HuseyinSimsek7904 — APPROVED** [review]
I love the animation!

**Comment by HuseyinSimsek7904** [comment]
Wait, I just realized, why are all 4 PR's chained? What does this PR have to do with #13?

**Comment by ErtyumPX** [comment]
@HuseyinSimsek7904 it's using the parts that are added in the previous PRs, like in `layout.tsx` and `Enter.tsx`, otherwise I would need to rewrite everything, and if the target branch was `main`, this PR would contain many parts that are also exist in the other PRs

**Review by Utkub24 — APPROVED** [review]
Yep, really nice animation. I especially like the fact that it doesn't restart when I go to a new page. However it resets when toggling themes. Could this be implemented?

**Comment by ErtyumPX** [comment]
Are we good to go with this one @HuseyinSimsek7904

**Review by HuseyinSimsek7904 — APPROVED** [review]
2nd approve...

**Pull request merged**
